// Auto-generated by scripts/write-build-info.mjs at build time.
// Do not edit by hand — `git status` is expected to show this file as
// modified after every build, and the next prebuild regenerates it.

export const VERSION = "0.1.0";
export const GIT_SHA = "c1727a2";
export const DIRTY = true;
export const BUILT_AT = "2026-05-27T15:50:25.697Z";
